### ISSUE TITLE
neuro demo ideas

### ISSUE THREAD

**Issue by clewis7** [fastplotlib/fastplotlib-fens2024#4]
- [ ] be able to page up and page down the calcium traces (key up events)
- [ ] when paging up and down the calcium trace, display the corresponding tuning curve
- [ ] have a region selector on the calcium traces with a zoomed in plot below, try to see head angle across packets of neural activity

**Comment by kushalkolar** [comment]
Reopening because need to recheck how linear selector allows this automatically
