### ISSUE TITLE
add image widget to demo?

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib-fens2024#7]
even though it seems like you're not using it in the neuro demo, would be good to tell people it's there, lazy scroll through Guillaume's dataset? Example with window func

**Comment by clewis7** [comment]
There is just already so much stuff, I'm not sure if there will be time

**Comment by clewis7** [comment]
I think the practice is super important, but dramatically slows things down and so it feels like it would be between showing the selectors and showing imagewidget...and we are using the selectors more in the neuro demo

**Comment by kushalkolar** [comment]
Yes but from experience it's something that people use _a lot_ after the workshop. I have a big video and I just want to view it and do a few simple things. Even if there isn't enough time it's in the demo for them to checkout later :)

**Comment by clewis7** [comment]
okay, I like the one with the zebra fish data... not sure how hard that would be to include in ccn repo
